### ISSUE TITLE
Passing parameters into the unity project

### ISSUE THREAD

**Issue by Betapig1** [azesmway/react-native-unity-play#1]
Is this package able to take in parameters to use in the unity project? Like let's say I needed a number to be put in from react native to unity, is that a thing the package is capable of doing?

**Comment by azesmway** [comment]
In the current version, I did not enable such a feature, I just needed to play the unity project. If this is required for you, I will do it in the next version.

**Comment by Betapig1** [comment]
It is required for me yes. Would this be able to be added somewhat quickly?

**Comment by azesmway** [comment]
I make for IOS ( I can not test )
Using 
```
import { UnityResponderView } from 'react-native-unity-play';
UnityResponderView.postMessage(gameObject, functionName, message)
```

**Comment by azesmway** [comment]
> It is required for me yes. Would this be able to be added somewhat quickly?

I make for IOS ( I can not test )
See the last commit

Using 
```
import { UnityResponderView } from 'react-native-unity-play';
UnityResponderView.postMessage(gameObject, functionName, message)
```
