### ISSUE TITLE
Black screen after closing and reopening app and restarting unity project

### ISSUE THREAD

**Issue by Betapig1** [azesmway/react-native-unity-play#3]
When I open the app and open the project then close the app. The next time I open the app and the project the project just shows a black screen

**Comment by azesmway** [comment]
> When I open the app and open the project then close the app. The next time I open the app and the project the project just shows a black screen

Please write in more detail. How do you close the application?

**Comment by Betapig1** [comment]
I close the application by opening the list if apps open, and swiping it closed

**Comment by azesmway** [comment]
Killing the application or removing it to the background?

**Comment by Betapig1** [comment]
Killing it completley i believe. The application is no longer open

**Comment by Betapig1** [comment]
The only way I can get the project to show again is to uninstall and rebuild the app

**Comment by azesmway** [comment]
I made a build apk and my test application which I posted with the link and with a real working unit project starts and closes without problems

**Comment by Betapig1** [comment]
Did you do it with a development build? Rather than a release apk?

**Comment by azesmway** [comment]
release apk

**Comment by Betapig1** [comment]
If you do it with a dev build you will probably find the same bug

**Comment by azesmway** [comment]
not, everything works in all variants

**Comment by Betapig1** [comment]
Well do you want some of my code? Which files would help you

**Comment by azesmway** [comment]
<img width="383" alt="image" src="https://user-images.githubusercontent.com/15251391/123310704-0d678780-d52f-11eb-8cd2-349cb922b8f3.png">

**Comment by Betapig1** [comment]
Okay I'll get that to you in about an hour if that works

**Comment by Betapig1** [comment]
here you are https://drive.google.com/file/d/1TV0qtKbJkO75ylrYnqwQxkwhcaUOJ4P0/view?usp=sharing

**Comment by azesmway** [comment]
https://drive.google.com/file/d/18l0K7FoHNm8_hMqXeno7ZRVabPbKHxue/view?usp=sharing

everything works fine
a problem with the screen because the settings from the description were not made

UNITY PLAYER SETTINGS
Resolution and Presentation -> Start in fullscreen mode -> no selection set !
Resolution and Presentation -> Render outside safe area -> no selection set !

**Comment by Betapig1** [comment]
Ah that makes sense. One more question, how do I include unity packages and assets? Becuase with a different project i get this `   > Could not find :native-toolkit:.
     Required by:
         project :app
         project :app > project :unityLibrary
   > Could not find :support-compat-27.1.1:.
     Required by:
         project :app
         project :app > project :unityLibrary
   > Could not find :support-v4-27.1.1:.
     Required by:
         project :app
         project :app > project :unityLibrary`

when i try to run it because it cant find the .aar files

**Comment by azesmway** [comment]
I beg your pardon - I did not understand the question

**Comment by Betapig1** [comment]
Certain unity assets attach .aar files in the libs folder and requires them. However when I load the project in react native it is unable to find them

**Comment by azesmway** [comment]
Create directory into android/app/libs
Copy libs from <project_name>/unity/builds/android/unityLibrary/libs/* to android/app/libs

Add to build.gradle

allprojects {
    repositories {
        flatDir {
            dirs "$rootDir/app/libs"
        }
