### ISSUE TITLE
[iOS] Is IPC implemented?

### ISSUE THREAD

**Issue by stockHuman** [azesmway/react-native-unity-play#9]
Hello!

Thanks for the library - It seems cleaner and more up to date than most other implementations of this particular RN<==>Unity challenge. Am I mistaken or is iOS communication not implemented? Using `postMessage` as in the docs results in _"TypeError: null is not an object (evaluating 'UnityNativeModule.postMessage')"_.

Cheers :)

**Comment by chanceeakin** [comment]
Hey y'all; I've opened up a PR for this behavior. Would one of you mind giving my PR a look? Mobile dev noob over here. 😄
